# Generated by Django 2.1 on 2018-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_info',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_no', models.PositiveIntegerField()),
                ('p_name', models.TextField()),
                ('desc', models.TextField()),
                ('donor_name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('h_no', models.PositiveIntegerField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
