# Generated by Django 2.1 on 2018-08-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_info_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donor_info',
            new_name='Donor',
        ),
    ]
