# Generated by Django 2.1 on 2018-08-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20180830_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Donors',
        ),
    ]
