# Generated by Django 2.1 on 2018-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20180830_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='country',
            field=models.CharField(default='India', editable='False', max_length=20),
        ),
    ]
