# Generated by Django 2.1 on 2018-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20180830_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
